///////////////////////////////////////////////////////////////////////////
///////// This file is generated by proto/gen_proto.py from ///////////////
///////// proto.txt and proto_data.txt, do not edit!!!		///////////////
///////////////////////////////////////////////////////////////////////////
package module

type MapUserMoveAsk struct {
	Userid int
	X int
	Y int
}
// 请在相应模块实现MapUserMoveAsk的处理函数
// func (self *MapUserMoveAsk) HandleMsg(pState *MapState) { }

func (self *UserMoveAsk) HandleMsg(pUserState *UserState) {
	if chMap, ok := MpMapCh[pUserState.User.Mapid]; ok {
		var ask = MapUserMoveAskPool.Get().(MapUserMoveAsk)
		ask.Userid = pUserState.User.Userid
		ask.X = self.X
		ask.Y = self.Y
		var msg MapMsg = &ask
		chMap <- msg
	}
}

type MapAttackAsk struct {
	Userid int
	Entityid int
}
// 请在相应模块实现MapAttackAsk的处理函数
// func (self *MapAttackAsk) HandleMsg(pState *MapState) { }

func (self *AttackAsk) HandleMsg(pUserState *UserState) {
	if chMap, ok := MpMapCh[pUserState.User.Mapid]; ok {
		var ask = MapAttackAskPool.Get().(MapAttackAsk)
		ask.Userid = pUserState.User.Userid
		ask.Entityid = self.Entityid
		var msg MapMsg = &ask
		chMap <- msg
	}
}

type MapPutBombAsk struct {
	Userid int
	X int
	Y int
}
// 请在相应模块实现MapPutBombAsk的处理函数
// func (self *MapPutBombAsk) HandleMsg(pState *MapState) { }

func (self *PutBombAsk) HandleMsg(pUserState *UserState) {
	if chMap, ok := MpMapCh[pUserState.User.Mapid]; ok {
		var ask = MapPutBombAskPool.Get().(MapPutBombAsk)
		ask.Userid = pUserState.User.Userid
		ask.X = self.X
		ask.Y = self.Y
		var msg MapMsg = &ask
		chMap <- msg
	}
}

