///////////////////////////////////////////////////////////////////////////
///////// This file is generated by proto/gen_proto.py from ///////////////
///////// proto.txt and proto_data.txt, do not edit!!!		///////////////
///////////////////////////////////////////////////////////////////////////
package module

const REGISTERASK = 10001
const REGISTERRSP = 10002
const LOGINASK = 10003
const LOGINRSP = 10004
const FRIENDASK = 10005
const FRIENDRSP = 10006
const RUOKASK = 10007
const RUOKRSP = 10008
const USERINTOMAPRSP = 10009
const ENTITYINTOMAPRSP = 10010
const ENTITYOUTMAPRSP = 10011
const USERMOVEASK = 10012
const ENTITYPOSRSP = 10013
const ATTACKASK = 10014
const ENTITYHPRSP = 10015
const PUTBOMBASK = 10016
const BOMBINRSP = 10017
const BOMBBLASTRSP = 10018

type FriendInfo struct {
	Userid int
	Name string
}

type EntityInfo struct {
	Entityid int
	EntityType int
	X int
	Y int
}

type RegisterAsk struct {
	Name string
	Passwd string
}

type RegisterRsp struct {
	OK bool
}

type LoginAsk struct {
	Name string
	Passwd string
}

type LoginRsp struct {
	OK bool
	Userid int
}

type FriendAsk struct {
}
// 请在相应模块实现FriendAsk的处理函数
// func (self *FriendAsk) HandleMsg(pState *UserState) { }

type FriendRsp struct {
	Ok bool
	IdList []int
	FriendList []FriendInfo
}

type RUOKAsk struct {
	Ok bool
}
// 请在相应模块实现RUOKAsk的处理函数
// func (self *RUOKAsk) HandleMsg(pState *UserState) { }

type RUOKRsp struct {
	OK bool
}

type UserIntoMapRsp struct {
	Mapid int
	X int
	Y int
	EntityList []EntityInfo
}

type EntityIntoMapRsp struct {
	Entity EntityInfo
}

type EntityOutMapRsp struct {
	Entityid int
}

type UserMoveAsk struct {
	X int
	Y int
}
type EntityPosRsp struct {
	EntityList []EntityInfo
}

type AttackAsk struct {
	Entityid int
}
type EntityHpRsp struct {
	Entityid int
	Hp int
}

type PutBombAsk struct {
	X int
	Y int
}
type BombInRsp struct {
	Bombid int
	X int
	Y int
}

type BombBlastRsp struct {
	Bombid int
}

