///////////////////////////////////////////////////////////////////////////
///////// This file is generated by proto/gen_proto.py from ///////////////
///////// proto.txt and proto_data.txt, do not edit!!!		///////////////
///////////////////////////////////////////////////////////////////////////
using UnityEngine;
using System.Collections.Generic;

static class PROTO_ID
{
	public const int REGISTERASK = 10001;
	public const int REGISTERRSP = 10002;
	public const int LOGINASK = 10003;
	public const int LOGINRSP = 10004;
	public const int FRIENDASK = 10005;
	public const int FRIENDRSP = 10006;
	public const int RUOKASK = 10007;
	public const int RUOKRSP = 10008;
	public const int USERINTOMAPRSP = 10009;
	public const int ENTITYINTOMAPRSP = 10010;
	public const int ENTITYOUTMAPRSP = 10011;
	public const int USERMOVEASK = 10012;
	public const int ENTITYPOSRSP = 10013;
	public const int ATTACKASK = 10014;
	public const int ENTITYHPRSP = 10015;
	public const int PUTBOMBASK = 10016;
	public const int BOMBINRSP = 10017;
	public const int BOMBBLASTRSP = 10018;
}

public class FriendInfo
{
	public int Userid;
	public string Name;
}

public class EntityInfo
{
	public int Entityid;
	public int EntityType;
	public int X;
	public int Y;
}

public class RegisterAsk
{
	public string Name;
	public string Passwd;
}

public class RegisterRsp
{
	public bool OK;
}

public class LoginAsk
{
	public string Name;
	public string Passwd;
}

public class LoginRsp
{
	public bool OK;
	public int Userid;
}

public class FriendAsk
{
}

public class FriendRsp
{
	public bool Ok;
	public List<int> IdList;
	public List<FriendInfo> FriendList;
}

public class RUOKAsk
{
	public bool Ok;
}

public class RUOKRsp
{
	public bool OK;
}

public class UserIntoMapRsp
{
	public int Mapid;
	public int X;
	public int Y;
	public List<EntityInfo> EntityList;
}

public class EntityIntoMapRsp
{
	public EntityInfo Entity;
}

public class EntityOutMapRsp
{
	public int Entityid;
}

public class UserMoveAsk
{
	public int X;
	public int Y;
}

public class EntityPosRsp
{
	public List<EntityInfo> EntityList;
}

public class AttackAsk
{
	public int Entityid;
}

public class EntityHpRsp
{
	public int Entityid;
	public int Hp;
}

public class PutBombAsk
{
	public int X;
	public int Y;
}

public class BombInRsp
{
	public int Bombid;
	public int X;
	public int Y;
}

public class BombBlastRsp
{
	public int Bombid;
}

